"""schema inicial

Revision ID: 23e474bf439a
Revises: 
Create Date: 2026-09-14 14:45:00.999762

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23e474bf439a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_fonte', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('paginas_conteudo', sa.Integer(), nullable=True),
    sa.Column('paginas_fisicas', sa.Integer(), nullable=True),
    sa.Column('capitulos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classificacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_hash_fonte'), 'book', ['hash_fonte'], unique=True)
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('senioridade', sa.String(), nullable=False),
    sa.Column('disponibilidade_horas', sa.Float(), nullable=False),
    sa.Column('plano', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_book_hash_fonte'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
